"""empty message

Revision ID: f35e43008c46
Revises: 
Create Date: 2025-12-20 10:30:51.378791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35e43008c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_created_by_id'), 'company', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_company_updated_by_id'), 'company', ['updated_by_id'], unique=False)
    op.create_table('camera',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('camera_guid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False, comment='axxon-next, trassir-cloud, trassir-server, etc.'),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB config for connection and provider script (including recorder version)'),
    sa.Column('provider_mode', sa.String(), nullable=False, comment='single or stream'),
    sa.Column('provider_image_folder', sa.String(), nullable=True, comment='Folder name for storing images'),
    sa.Column('provider_cron_scheme', sa.String(), nullable=True, comment='CronTab job schedule string'),
    sa.Column('collection_interval', sa.String(), nullable=True, comment='Time range for video stream collection (e.g., 8:00-20:00)'),
    sa.Column('screenshot_interval', sa.Integer(), nullable=True, comment='Interval between screenshots in minutes (e.g., 10)'),
    sa.Column('crop_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Screenshot crop zones configuration'),
    sa.Column('reference_image_url', sa.String(), nullable=True, comment='Reference/standard image URL'),
    sa.Column('kpi_threshold', sa.Float(), nullable=True, comment='KPI threshold (red line) - send notification below this percentage'),
    sa.Column('notification_chat_id', sa.String(), nullable=True, comment='Chat ID for violation notifications'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of attempts to download image'),
    sa.Column('retry_timeout', sa.Integer(), nullable=False, comment='Timeout between retry attempts in seconds'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_camera_guid'), 'camera', ['camera_guid'], unique=False)
    op.create_index(op.f('ix_camera_company_id'), 'camera', ['company_id'], unique=False)
    op.create_index(op.f('ix_camera_created_by_id'), 'camera', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_camera_updated_by_id'), 'camera', ['updated_by_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('fill_percentage', sa.Float(), nullable=True),
    sa.Column('compliance_percentage', sa.Float(), nullable=True),
    sa.Column('screenshot_s3_url', sa.String(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_camera_id'), 'report', ['camera_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_report_id'), 'notification', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_report_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_report_camera_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_camera_updated_by_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_created_by_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_company_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_camera_guid'), table_name='camera')
    op.drop_table('camera')
    op.drop_index(op.f('ix_company_updated_by_id'), table_name='company')
    op.drop_index(op.f('ix_company_created_by_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
